### ISSUE TITLE
runing the (A) w/o PT meet the erro（omegaconf.errors.ConfigKeyError: Key 'multiple_train_files' not in 'AudioPretrainingConfig'）

### ISSUE THREAD

**Issue by foolishcqx** [Yuto-Matsunaga/Prompt_Tuning_for_Audio_Deepfake_Detection#1]
Traceback (most recent call last):
  File "e:/Audio_deepfake/code/Prompt_Tuning_for_Audio_Deepfake_Detection-main/W2V_prompt_tuning/prompt_tuning.py", line 383, in <module>  
    model = load_model(config, config["device"])
  File "e:/Audio_deepfake/code/Prompt_Tuning_for_Audio_Deepfake_Detection-main/W2V_prompt_tuning/prompt_tuning.py", line 177, in load_model
    model = Model(config, device)
  File "e:\Audio_deepfake\code\Prompt_Tuning_for_Audio_Deepfake_Detection-main\W2V_prompt_tuning\model.py", line 483, in __init__
    self.ssl_model = SSLModel(self.device)
  File "e:\Audio_deepfake\code\Prompt_Tuning_for_Audio_Deepfake_Detection-main\W2V_prompt_tuning\model.py", line 53, in __init__
    model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])
  File "D:\Anaconda\envs\AudioDeepfake\lib\site-packages\fairseq\checkpoint_utils.py", line 436, in load_model_ensemble_and_task
    task = tasks.setup_task(cfg.task)
  File "D:\Anaconda\envs\AudioDeepfake\lib\site-packages\fairseq\tasks\__init__.py", line 39, in setup_task
    cfg = merge_with_parent(dc(), cfg)
  File "D:\Anaconda\envs\AudioDeepfake\lib\site-packages\fairseq\dataclass\utils.py", line 500, in merge_with_parent
    merged_cfg = OmegaConf.merge(dc, cfg)
  File "D:\Anaconda\envs\AudioDeepfake\lib\site-packages\omegaconf\omegaconf.py", line 321, in merge
    target.merge_with(*others[1:])
  File "D:\Anaconda\envs\AudioDeepfake\lib\site-packages\omegaconf\basecontainer.py", line 331, in merge_with
  File "D:\Anaconda\envs\AudioDeepfake\lib\site-packages\omegaconf\base.py", line 95, in _format_and_raise
    format_and_raise(
  File "D:\Anaconda\envs\AudioDeepfake\lib\site-packages\omegaconf\_utils.py", line 629, in format_and_raise
    _raise(ex, cause)
  File "D:\Anaconda\envs\AudioDeepfake\lib\site-packages\omegaconf\_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
  File "D:\Anaconda\envs\AudioDeepfake\lib\site-packages\omegaconf\basecontainer.py", line 329, in merge_with
    self._merge_with(*others)
  File "D:\Anaconda\envs\AudioDeepfake\lib\site-packages\omegaconf\basecontainer.py", line 347, in _merge_with
    BaseContainer._map_merge(self, other)
  File "D:\Anaconda\envs\AudioDeepfake\lib\site-packages\omegaconf\basecontainer.py", line 314, in _map_merge
    dest[key] = src._get_node(key)
  File "D:\Anaconda\envs\AudioDeepfake\lib\site-packages\omegaconf\dictconfig.py", line 258, in __setitem__
    self._format_and_raise(
  File "D:\Anaconda\envs\AudioDeepfake\lib\site-packages\omegaconf\base.py", line 95, in _format_and_raise
    format_and_raise(
  File "D:\Anaconda\envs\AudioDeepfake\lib\site-packages\omegaconf\_utils.py", line 629, in format_and_raise
    _raise(ex, cause)
  File "D:\Anaconda\envs\AudioDeepfake\lib\site-packages\omegaconf\_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigKeyError: Key 'multiple_train_files' not in 'AudioPretrainingConfig'
        full_key: multiple_train_files
        reference_type=Optional[AudioPretrainingConfig]
        object_type=AudioPretrainingConfig

**Comment by foolishcqx** [comment]
Have you ever encountered this problem, and if so, can you tell me how you solved it, thank you very much!

**Comment by Yuto-Matsunaga** [comment]
Sorry for the delay in replying.
I've never encountered this problem.

**Comment by foolishcqx** [comment]
Thanks for the reply, this issue has been resolved
